version: 0.2

phases:
  install:
    runtime-versions: 
        nodejs: 8
    commands:
      - echo Build enviromment `uname -a` `aws --version 2>&1` node/`node --version` npm/`npm --version`
      - npm install
#       - pip install --upgrade awscli
  pre_build:
    commands:
      - npm test
  build:
    commands:
      - npm run build
#        - aws cloudformation package --template dist/package/template.yml --s3-bucket nodegeethika --output-template template-export.yml
#   post_build:
#     commands:
      
#       - aws cloudformation package --template-file template.yml --s3-bucket nodegeethika --output-template-file template-export.yml

#         - aws cloudformation package
#         --template dist/package/template.yml
#         --s3-bucket nodegeethika
#         --output-template template-export.yml

artifacts:
  type: ""
  path: /
  files:
    -template.yml
    - template-export.yml
